### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'bbox_txt/images\\img3.txt'

### ISSUE THREAD

**Issue by andikira** [Cartucho/yolo-boundingbox-labeler-GUI#13]
Hello thanks for your work, 
but i have some problem. when the UI is open and i try to make bounding box in example image the program got error (Not responding), it says :  

 File "D:/andiki/yolo-boundingbox-labeler-GUI-master/run.py", line 105, in save_bb
    with open(txt_path, 'a') as myfile:

FileNotFoundError: [Errno 2] No such file or directory: 'bbox_txt/images\\img3.txt'

i use 
spyder 3.2.3
python 3.6
opencv 3.4.1
numpy 1.11.3

thanks in advance sir

**Comment by Cartucho** [comment]
@andikira Could you check if it works now? I committed an update

**Comment by Cartucho** [comment]
![image](https://user-images.githubusercontent.com/15831541/37723589-acb5a830-2d26-11e8-8120-65199afcb59b.png)

**Comment by andikira** [comment]
@Cartucho You Save My Life Sir !!
Thank you so much for fast response and your help
its work perfectly
