### ISSUE TITLE
TypeError: Scalar value for argument 'color' is not numeric

### ISSUE THREAD

**Issue by MattKleinsmith** [Cartucho/yolo-boundingbox-labeler-GUI#4]
**Actions:**

```
ipython run.py
Click anywhere
```

**Error:**
```
--> 245             cv2.rectangle(tmp_img, point_1, (mouse_x, mouse_y), color, 2)
TypeError: Scalar value for argument 'color' is not numeric
```
**Workaround:**

Pull request: https://github.com/Cartucho/yolo-boundingbox-labeler-GUI/pull/5/files

Description: Add `.tolist()` to `color`.

**Environment:**

Ubuntu 16.04, Python 3.6.3, Anaconda 5.0.1, OpenCV 3.4.0

**Comment by Cartucho** [comment]
Thanks! @MattKleinsmith
