### ISSUE TITLE
Can't delete box if created bottom right point first

### ISSUE THREAD

**Issue by MattKleinsmith** [Cartucho/yolo-boundingbox-labeler-GUI#7]
Warning: Click the top right point first, if using the current version of the repo.

Solution 1: Swap point_1 with point_2 if point_1 is the bottom right point. This solution will help with the VOC danger mentioned here: https://github.com/Cartucho/yolo-boundingbox-labeler-GUI/pull/6

Solution 2: Modify get_close_icon and draw_close_icon, and any other related functions

**Comment by Cartucho** [comment]
@MattKleinsmith I noticed this yesterday!
My idea to solve is:
- The bounding box only shows the "delete" button if currently selected
- To select the bounding box we must do a double click

**Comment by Cartucho** [comment]
Selecting the bbox would also be great since we could later add an option to quickly resize and re-label the bounding box.

**Comment by Cartucho** [comment]
@MattKleinsmith I will fix this first! I'm working on it!

**Comment by Cartucho** [comment]
@MattKleinsmith 
It's done, now we can only delete if we select that bbox, it also deals with multiple bboxes goes for the smaller one:
![screenshot from 2018-02-16 16-39-23](https://user-images.githubusercontent.com/15831541/36318642-5ebc64b4-1338-11e8-983e-e2f90ee04e62.png)

I'm not sure if I thought of all the possible cases, but it is surely more robust now.
